### ISSUE TITLE
Register-Frontend

### ISSUE THREAD

**Issue by mousavi-lg** [mousavi-lg/social-media#1]
When I post something from frontend (/register) it doesn't work but I know API works. @m-moein98

**Comment by mousavi-lg** [comment]
When I post something from frontend (/register) it doesn't work but I know API works. @m-moein98

**Comment by m-moein98** [comment]
ill check it out and fix it for you @mousavi-lg

**Comment by mousavi-lg** [comment]
Thanks for fixing these problems.
